// CommonJS router index
const { Router } = require('express');
const authRoutes = require('./auth.routes');
const propertyRoutes = require('./property.routes');
const bookingRoutes = require('./booking.routes');
const ownerRoutes = require('./owner.routes');
const agentRoutes = require('./agent.routes');
const travelerRoutes = require('./traveler.routes');
const favoritesRoutes = require('./favorites.routes');

const router = Router();
router.use('/auth', authRoutes); // -> /api/auth/...
router.use('/properties', propertyRoutes); // -> /api/properties/...
router.use('/bookings', bookingRoutes); // -> /api/bookings/...
router.use('/owner', ownerRoutes); // -> /api/owner/...
router.use('/agent', agentRoutes); // -> /api/agent/...
router.use('/traveler', travelerRoutes); // -> /api/traveler/...
router.use('/favorites', favoritesRoutes); // -> /api/favorites/...

module.exports = router;
